name: CI check
on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
      - "LICENSE"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      # Set fetch-depth: 0 to fetch commit history and tags for use in version calculation
      - name: Check out code
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
          submodules: true

      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.18.1

      - name: Run tests
        shell: bash
        run: make test

  build:
    needs: [test]
    runs-on: ubuntu-20.04
    container:
      image: tinygo/tinygo:0.23.0
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.18.1"

      - name: Check out code
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
          submodules: true

      # TinyGo's release container does not have Make command.
      - name: Install Make
        run: apt install make

      - name: Build WASM filter
        shell: bash
        run: make build
